[tool.black]
target = "py310"
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
branch = true
source = ["."]
omit = [
    "*/tests/*.py",
    "*/test_*.py",
    "*/tests.py"
]
