name: CI

on: [ push ]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install -r requirements.txt

      - name: Run linter
        run: flake8

      - name: Run tests
        run: nosetests -v --with-coverage --cover-package=huawei
