name: CI

on: [ push, pull_request ]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: Run linter
        run: flake8

      - name: Run tests
        run: pytest --cov=huawei --cov-report=term
